version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: anime
      POSTGRES_USER: anime
      POSTGRES_PASSWORD: anime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - anime-net
      

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    networks:
      - anime-net

  scrapper:
    build: ../scrapper
    command: ["python", "-m", "scrapper.run"]
    depends_on:
      - postgres
      - redis
    networks:
      - anime-net

  ai:
    build: ../ai
    command: ["python", "-m", "ai.server"]
    depends_on:
      - redis
      - postgres
    networks:
      - anime-net

  api:
    build: ../gateway
    command: ["uvicorn", "gateway.main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - anime-net

volumes:
  postgres_data:

networks:
  anime-net:
    driver: bridge
